export const BUSINESS_INFO = {
  name: 'Distributeur Chips 09',
  arabicName: 'موزع الشيبس 09',
  description: 'الموزع المعتمد لرقائق الشيبس بالجملة في الجزائر - خدمة التوزيع للمحلات والمتاجر وتجار التجزئة',
  email: 'depotchips81@gmail.com',
  phone: '0541655938',
  phoneInternational: '+213541655938',
  whatsapp: '+213541655938',
  whatsappUrl: 'https://wa.me/213541655938',
  location: 'الجزائر - توصيل لجميع الولايات',
  productionUrl: 'https://distributeur-chips-09.vercel.app',
  defaultMinOrderCartons: 1,
};

export const REAL_BRANDS = [
  {
    name: 'Master Chips',
    arabicName: 'ماستر شيبس',
    slug: 'master-chips',
    description: 'أجود أنواع الشيبس المقرمش بنكهات متعددة',
    color: '#1e40af',
  },
  {
    name: 'Mahboul',
    arabicName: 'مهبول',
    slug: 'mahboul',
    description: 'شيبس بنكهات مميزة ومحبوبة لدى المستهلك الجزائري',
    color: '#dc2626',
  },
  {
    name: 'Rifkus',
    arabicName: 'ريكوس',
    slug: 'rifkus',
    description: 'رقائق بطاطس طبيعية مقرمشة وشهية',
    color: '#ca8a04',
  },
  {
    name: 'Dadi',
    arabicName: 'دادي',
    slug: 'dadi',
    description: 'شيبس وسناكس بنكهات تقليدية وعصرية',
    color: '#b91c1c',
  },
  {
    name: 'Tifouf',
    arabicName: 'تيفوف',
    slug: 'tifouf',
    description: 'منتجات مقرمشة بأسعار تنافسية وجودة عالية',
    color: '#0f766e',
  },
];

export const REAL_FLAVORS = [
  { name: 'Cheese', arabicName: 'جبنة', slug: 'cheese', color: '#eab308' },
  { name: 'Spicy', arabicName: 'حار', slug: 'spicy', color: '#ef4444' },
  { name: 'Hot Chili', arabicName: 'شل حار', slug: 'hot-chili', color: '#b91c1c' },
  { name: 'Barbecue', arabicName: 'شواء', slug: 'barbecue', color: '#78350f' },
  { name: 'Pizza', arabicName: 'بيتزا', slug: 'pizza', color: '#f97316' },
  { name: 'Ketchup', arabicName: 'كاتشب', slug: 'ketchup', color: '#dc2626' },
  { name: 'Chicken', arabicName: 'دجاج', slug: 'chicken', color: '#d97706' },
  { name: 'Peanut', arabicName: 'فول سوداني', slug: 'peanut', color: '#a16207' },
  { name: 'Salt & Vinegar', arabicName: 'خل و ملح', slug: 'salt-vinegar', color: '#0284c7' },
];

export interface WilayaItem {
  code: string;
  name: string;
}

export const ALGERIA_WILAYAS: WilayaItem[] = [
  { code: '01', name: 'أدرار - Adrar' },
  { code: '02', name: 'الشلف - Chlef' },
  { code: '03', name: 'الأغواط - Laghouat' },
  { code: '04', name: 'أم البواقي - Oum El Bouaghi' },
  { code: '05', name: 'باتنة - Batna' },
  { code: '06', name: 'بجاية - Béjaïa' },
  { code: '07', name: 'بسكرة - Biskra' },
  { code: '08', name: 'بشار - Béchar' },
  { code: '09', name: 'البليدة - Blida' },
  { code: '10', name: 'البويرة - Bouira' },
  { code: '11', name: 'تمنراست - Tamanrasset' },
  { code: '12', name: 'تبسة - Tébessa' },
  { code: '13', name: 'تلمسان - Tlemcen' },
  { code: '14', name: 'تيارت - Tiaret' },
  { code: '15', name: 'تيزي وزو - Tizi Ouzou' },
  { code: '16', name: 'الجزائر العاصمة - Alger' },
  { code: '17', name: 'الجلفة - Djelfa' },
  { code: '18', name: 'جيجل - Jijel' },
  { code: '19', name: 'سطيف - Sétif' },
  { code: '20', name: 'سعيدة - Saïda' },
  { code: '21', name: 'سكيكدة - Skikda' },
  { code: '22', name: 'سيدي بلعباس - Sidi Bel Abbès' },
  { code: '23', name: 'عنابة - Annaba' },
  { code: '24', name: 'قالمة - Guelma' },
  { code: '25', name: 'قسنطينة - Constantine' },
  { code: '26', name: 'المدية - Médéa' },
  { code: '27', name: 'مستغانم - Mostaganem' },
  { code: '28', name: 'المسيلة - M\'Sila' },
  { code: '29', name: 'معسكر - Mascara' },
  { code: '30', name: 'ورقلة - Ouargla' },
  { code: '31', name: 'وهران - Oran' },
  { code: '32', name: 'البيض - El Bayadh' },
  { code: '33', name: 'إليزي - Illizi' },
  { code: '34', name: 'برج بوعريريج - Bordj Bou Arreridj' },
  { code: '35', name: 'بومرداس - Boumerdès' },
  { code: '36', name: 'الطارف - El Tarf' },
  { code: '37', name: 'تندوف - Tindouf' },
  { code: '38', name: 'تيسمسيلت - Tissemsilt' },
  { code: '39', name: 'الوادي - El Oued' },
  { code: '40', name: 'خنشلة - Khenchela' },
  { code: '41', name: 'سوق أهراس - Souk Ahras' },
  { code: '42', name: 'تيبازة - Tipaza' },
  { code: '43', name: 'ميلة - Mila' },
  { code: '44', name: 'عين الدفلى - Aïn Defla' },
  { code: '45', name: 'النعامة - Naâma' },
  { code: '46', name: 'عين تموشنت - Aïn Témouchent' },
  { code: '47', name: 'غرداية - Ghardaïa' },
  { code: '48', name: 'غليزان - Relizane' },
  { code: '49', name: 'تيميمون - Timimoun' },
  { code: '50', name: 'برج باجي مختار - Bordj Badji Mokhtar' },
  { code: '51', name: 'أولاد جلال - Ouled Djellal' },
  { code: '52', name: 'بني عباس - Béni Abbès' },
  { code: '53', name: 'عين صالح - In Salah' },
  { code: '54', name: 'عين قزام - In Guezzam' },
  { code: '55', name: 'تقرت - Touggourt' },
  { code: '56', name: 'جانت - Djanet' },
  { code: '57', name: 'المغير - El M\'Ghair' },
  { code: '58', name: 'المنيعة - El Meniaa' },
];

export const WILAYAS = ALGERIA_WILAYAS;

export const ORDER_STATUS_MAP: Record<string, { label: string; color: string; step: number }> = {
  pending: { label: 'طلب جديد', color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30', step: 1 },
  confirmed: { label: 'تم التأكيد', color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', step: 2 },
  preparing: { label: 'قيد التحضير', color: 'bg-amber-500/20 text-amber-400 border-amber-500/30', step: 3 },
  out_for_delivery: { label: 'خرج للتوصيل', color: 'bg-purple-500/20 text-purple-400 border-purple-500/30', step: 4 },
  delivered: { label: 'تم التسليم', color: 'bg-green-500/20 text-green-400 border-green-500/30', step: 5 },
  cancelled: { label: 'ملغي', color: 'bg-red-500/20 text-red-400 border-red-500/30', step: 0 },
};
