import { Product, Brand, Flavor } from '@/types';

export const AUTHENTIC_BRANDS: Brand[] = [
  {
    id: 'brand-1',
    name: 'Master Chips',
    arabicName: 'ماستر شيبس',
    slug: 'master-chips',
    description: 'أجود أنواع الشيبس المقرمش بنكهات متعددة وجودة ممتازة',
    active: true,
  },
  {
    id: 'brand-2',
    name: 'Mahboul',
    arabicName: 'مهبول',
    slug: 'mahboul',
    description: 'شيبس بنكهات مميزة ومحبوبة لدى المستهلك الجزائري',
    active: true,
  },
  {
    id: 'brand-3',
    name: 'Rifkus',
    arabicName: 'ريكوس',
    slug: 'rifkus',
    description: 'رقائق بطاطس طبيعية مقرمشة وشهية بأعلى معايير الجودة',
    active: true,
  },
  {
    id: 'brand-4',
    name: 'Dadi',
    arabicName: 'دادي',
    slug: 'dadi',
    description: 'شيبس وسناكس بنكهات تقليدية وعصرية مميزة',
    active: true,
  },
  {
    id: 'brand-5',
    name: 'Tifouf',
    arabicName: 'تيفوف',
    slug: 'tifouf',
    description: 'منتجات مقرمشة بأسعار تنافسية وجودة عالية',
    active: true,
  },
];

export const AUTHENTIC_FLAVORS: Flavor[] = [
  { id: 'flav-1', name: 'Cheese', arabicName: 'جبنة', slug: 'cheese', color: '#eab308', active: true },
  { id: 'flav-2', name: 'Spicy', arabicName: 'حار', slug: 'spicy', color: '#ef4444', active: true },
  { id: 'flav-3', name: 'Hot Chili', arabicName: 'شل حار', slug: 'hot-chili', color: '#b91c1c', active: true },
  { id: 'flav-4', name: 'Barbecue', arabicName: 'شواء', slug: 'barbecue', color: '#78350f', active: true },
  { id: 'flav-5', name: 'Pizza', arabicName: 'بيتزا', slug: 'pizza', color: '#f97316', active: true },
  { id: 'flav-6', name: 'Ketchup', arabicName: 'كاتشب', slug: 'ketchup', color: '#dc2626', active: true },
  { id: 'flav-7', name: 'Chicken', arabicName: 'دجاج', slug: 'chicken', color: '#d97706', active: true },
  { id: 'flav-8', name: 'Peanut', arabicName: 'فول سوداني', slug: 'peanut', color: '#a16207', active: true },
  { id: 'flav-9', name: 'Salt & Vinegar', arabicName: 'خل و ملح', slug: 'salt-vinegar', color: '#0284c7', active: true },
];

export const AUTHENTIC_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Master Chips Cheese',
    arabicName: 'ماستر شيبس جبنة',
    slug: 'master-chips-cheese',
    brandId: 'brand-1',
    brand: AUTHENTIC_BRANDS[0],
    flavorId: 'flav-1',
    flavor: AUTHENTIC_FLAVORS[0],
    category: 'chips',
    description: 'كرتون ماستر شيبس بنكهة الجبنة اللذيذة، يحتوي على 20 كيس.',
    imageUrl: null,
    unitPrice: 90,
    cartonQuantity: 20,
    cartonPrice: 1800,
    stock: 45,
    active: true,
    featured: true,
  },
  {
    id: 'prod-2',
    name: 'Master Chips Hot Chili',
    arabicName: 'ماستر شيبس شل حار',
    slug: 'master-chips-hot-chili',
    brandId: 'brand-1',
    brand: AUTHENTIC_BRANDS[0],
    flavorId: 'flav-3',
    flavor: AUTHENTIC_FLAVORS[2],
    category: 'chips',
    description: 'كرتون ماستر شيبس بنكهة الفلفل الحار، يحتوي على 20 كيس.',
    imageUrl: null,
    unitPrice: 90,
    cartonQuantity: 20,
    cartonPrice: 1800,
    stock: 35,
    active: true,
    featured: true,
  },
  {
    id: 'prod-3',
    name: 'Rifkus Spicy',
    arabicName: 'ريكوس حار',
    slug: 'rifkus-spicy',
    brandId: 'brand-3',
    brand: AUTHENTIC_BRANDS[2],
    flavorId: 'flav-2',
    flavor: AUTHENTIC_FLAVORS[1],
    category: 'chips',
    description: 'كرتون ريكوس حار المقرمش، يحتوي على 20 كيس شيبس.',
    imageUrl: null,
    unitPrice: 80,
    cartonQuantity: 20,
    cartonPrice: 1600,
    stock: 50,
    active: true,
    featured: true,
  },
  {
    id: 'prod-4',
    name: 'Mahboul Cheese',
    arabicName: 'مهبول جبنة',
    slug: 'mahboul-cheese',
    brandId: 'brand-2',
    brand: AUTHENTIC_BRANDS[1],
    flavorId: 'flav-1',
    flavor: AUTHENTIC_FLAVORS[0],
    category: 'chips',
    description: 'كرتون شيبس مهبول الأصلي بنكهة الجبنة، يحتوي على 20 كيس.',
    imageUrl: null,
    unitPrice: 85,
    cartonQuantity: 20,
    cartonPrice: 1700,
    stock: 60,
    active: true,
    featured: true,
  },
  {
    id: 'prod-5',
    name: 'Dadi Barbecue',
    arabicName: 'دادي شواء',
    slug: 'dadi-barbecue',
    brandId: 'brand-4',
    brand: AUTHENTIC_BRANDS[3],
    flavorId: 'flav-4',
    flavor: AUTHENTIC_FLAVORS[3],
    category: 'chips',
    description: 'كرتون شيبس دادي بنكهة الشواء، كرتون 20 قطعة.',
    imageUrl: null,
    unitPrice: 105,
    cartonQuantity: 20,
    cartonPrice: 2100,
    stock: 25,
    active: true,
    featured: true,
  },
  {
    id: 'prod-6',
    name: 'Tifouf Cheese',
    arabicName: 'تيفوف جبنة',
    slug: 'tifouf-cheese',
    brandId: 'brand-5',
    brand: AUTHENTIC_BRANDS[4],
    flavorId: 'flav-1',
    flavor: AUTHENTIC_FLAVORS[0],
    category: 'chips',
    description: 'كرتون مقرمشات تيفوف بنكهة الجبنة اللذيذة، 20 قطعة.',
    imageUrl: null,
    unitPrice: 80,
    cartonQuantity: 20,
    cartonPrice: 1600,
    stock: 40,
    active: true,
    featured: true,
  },
  {
    id: 'prod-7',
    name: 'Master Chips Barbecue',
    arabicName: 'ماستر شيبس شواء',
    slug: 'master-chips-barbecue',
    brandId: 'brand-1',
    brand: AUTHENTIC_BRANDS[0],
    flavorId: 'flav-4',
    flavor: AUTHENTIC_FLAVORS[3],
    category: 'chips',
    description: 'كرتون ماستر شيبس بنكهة الشواء اللذيذة، 20 قطعة.',
    imageUrl: null,
    unitPrice: 95,
    cartonQuantity: 20,
    cartonPrice: 1900,
    stock: 30,
    active: true,
    featured: false,
  },
  {
    id: 'prod-8',
    name: 'Rifkus Ketchup',
    arabicName: 'ريكوس كاتشب',
    slug: 'rifkus-ketchup',
    brandId: 'brand-3',
    brand: AUTHENTIC_BRANDS[2],
    flavorId: 'flav-6',
    flavor: AUTHENTIC_FLAVORS[5],
    category: 'chips',
    description: 'كرتون ريكوس بنكهة الكاتشب المميزة، 20 قطعة.',
    imageUrl: null,
    unitPrice: 80,
    cartonQuantity: 20,
    cartonPrice: 1600,
    stock: 40,
    active: true,
    featured: false,
  },
];
