declare module 'lucide-react' {
  import * as React from 'react';
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
    className?: string;
  }
  export type LucideIcon = React.FC<LucideProps>;
  export const ShoppingBag: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const User: LucideIcon;
  export const Users: LucideIcon;
  export const UserPlus: LucideIcon;
  export const Menu: LucideIcon;
  export const X: LucideIcon;
  export const LogOut: LucideIcon;
  export const Package: LucideIcon;
  export const PackageOpen: LucideIcon;
  export const PackageCheck: LucideIcon;
  export const FileText: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Phone: LucideIcon;
  export const PhoneCall: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Trash2: LucideIcon;
  export const Plus: LucideIcon;
  export const Minus: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const ArrowDownRight: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const Eye: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Clock: LucideIcon;
  export const Truck: LucideIcon;
  export const Check: LucideIcon;
  export const XCircle: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Layers: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Boxes: LucideIcon;
  export const Newspaper: LucideIcon;
  export const Tag: LucideIcon;
  export const Settings: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Headphones: LucideIcon;
  export const Award: LucideIcon;
  export const BadgePercent: LucideIcon;
  export const Warehouse: LucideIcon;
  export const Handshake: LucideIcon;
  export const Send: LucideIcon;
  export const Printer: LucideIcon;
  export const Lock: LucideIcon;
  export const KeyRound: LucideIcon;
  export const Globe: LucideIcon;
  export const Bell: LucideIcon;
  export const Edit2: LucideIcon;
  export const Edit3: LucideIcon;
  export const Loader2: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Heart: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Banknote: LucideIcon;
  export const Building2: LucideIcon;
  const icons: Record<string, LucideIcon>;
  export default icons;
}
